In [1]:
import numpy as np

### Ejercicio 13
Determine si la siguiente matriz es singular:
$$\mathbf{A}=\begin{pmatrix}
    2.1 & -0.6 & 1.1\\
    3.2 & 4.7 & -0.8\\
    3.1 & -6.5 & 4.1
    \end{pmatrix}$$

In [2]:
A=np.array([[2.1,-0.6,1.1],[3.2, 4.7,-0.8],[3.1,-6.5,4.1]])
print("El determinante de la matriz es",np.linalg.det(A))

El determinante de la matriz es 0.0


Como $|\mathbf{A}|=0$, la matriz es singular.
### Ejercicio 14
Determine si la siguiente matriz es singular:
$$
    \mathbf{B}=\begin{pmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    -4 & 3 & -2 & 1\\
    8 & -7 & 6 & -5
    \end{pmatrix}
$$

In [3]:
B=np.array([[1,2,3,4],[5,6,7,8],[-4,3,-2,1],[8,-7,6,-5]])
print("El determinante de la matriz es",np.linalg.det(B))

El determinante de la matriz es -256.00000000000017


Como $|\mathbf{A}|\neq 0$, la matriz es no singular.
### Ejercicio 15
Resuelva el sistema $\mathbf{Ax=b}$, donde
$$
    \mathbf{A}=\begin{pmatrix}
    8 & -6 & 2\\
    -4 & 11 & -7\\
    4 & -7 & 6
    \end{pmatrix}
    \qquad
    \mathbf{b}=\begin{pmatrix}
    28\\
    -40\\
    33
    \end{pmatrix}
$$
sabiendo que la descomposición LU de la matriz de coeficientes es
$$
    \mathbf{A=LU}=\begin{pmatrix}
    2 & 0 & 0\\
    -1 & 2 & 0\\
    1 & -1 & 1
    \end{pmatrix}
    \begin{pmatrix}
    4 & -3 & 1\\
    0 & 4 & -3\\
    0 & 0 & 2
    \end{pmatrix}
$$

In [4]:
A=np.array([[8,-6,2],[-4,11,-7],[4,-7,6]])
b=np.array([28,-40,33])
L=np.array([[2,0,0],[-1,2,0],[1,-1,1]])
U=np.array([[4,-3,1],[0,4,-3],[0,0,2]])

Comprobemos primero la descomposición LU dada:

In [5]:
print(L@U)

[[ 8 -6  2]
 [-4 11 -7]
 [ 4 -7  6]]


Solucionamos entonces el sistema $\mathbf{Ly=b}$:

In [6]:
y=np.linalg.solve(L,b)
print(y)

[ 14. -13.   6.]


Obtenemos ahora la solución al sistema inicial resolviendo $\mathbf{Ux=y}$:

In [7]:
x=np.linalg.solve(U,y)
print("La solución del sistema es ",x)

La solución del sistema es  [ 2. -1.  3.]
