In [1]:
import numpy as np

def swapRows(v,i,j):
    
    if len(v.shape) == 1:
        v[i],v[j] = v[j],v[i]
    else:
        v[[i,j],:] = v[[j,i],:]
        
def swapCols(v,i,j):
    v[:,[i,j]] = v[:,[j,i]]

In [2]:
def LUdecomp(a,tol=1.0e-9):
    n = len(a)
    seq = np.array(range(n))
    
    #Calculando los factores de escala
    s = np.zeros((n))
    for i in range(n):
        s[i] = max(abs(a[i,:]))
        
    for k in range(0,n-1):
        #Intercambio de filas si es necesario
        p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k
        if abs(a[p,k]) < tol: 
            error.err("La matriz es singular.")
        if p != k:
            swapRows(s,k,p)
            swapRows(a,k,p)
            swapRows(seq,k,p)
        
        #Eliminación
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a[i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a,seq

def LUsolve(a,b,seq):
    n = len(a)
    
    #Rearreglando el vector b
    x = b.copy()
    for i in range(n):
        x[i] = b[seq[i]]
        
    #Solución
    for k in range(1,n):
        x[k] = x[k] - np.dot(a[k,0:k],x[0:k])
    x[n-1] = x[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        x[k] = (x[k] - np.dot(a[k,k+1:n],x[k+1:n]))/a[k,k]
    return x

In [3]:
def LUdecomp3(c,d,e):
    "c,d,e = LUdecomp3(c,d,e).\n Descomposición LU de una matriz triagonal conformada por las diagonales c,d,e."
    n = len(d)
    for k in range(1,n):
        lam = c[k-1]/d[k-1]
        d[k] = d[k] - lam*e[k-1]
        c[k-1] = lam
    return c,d,e

def LUsolve3(c,d,e,b):
    "x=LUsolve3(c,d,e,b).\n Resuelve Ax=b donde c,d,e son las diagonales descompuestas de la matriz triagonal A."
    n = len(d)
    for k in range(1,n):
        b[k] = b[k] - c[k-1]*b[k-1]
    b[n-1] = b[n-1]/d[n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - e[k]*b[k+1])/d[k]
    return b

### Ejemplo 24
Invierta la matriz $\mathbf{A}$ usando descomposición LU con pivote.
$$
    \mathbf{A}=\begin{pmatrix}
    0.6 & -0.4 & 1.0\\
    -0.3 & 0.2 & 0.5\\
    0.6 & -1.0 & 0.5
    \end{pmatrix}
$$

In [4]:
def matInv(a):
    n = len(a[0])
    aInv = np.identity(n)
    a,seq = LUdecomp(a)
    for i in range(n):
        aInv[:,i] = LUsolve(a,aInv[:,i],seq)
    return aInv

A = np.array([[ 0.6, -0.4, 1.0],[-0.3, 0.2, 0.5],[ 0.6, -1.0, 0.5]])
print("Ainv =\n",matInv(A))

Ainv =
 [[ 1.66666667 -2.22222222 -1.11111111]
 [ 1.25       -0.83333333 -1.66666667]
 [ 0.5         1.          0.        ]]


### Ejemplo 25
Invierta la matriz $\mathbf{A}$.
$$
    \mathbf{A}=\begin{pmatrix}
    2 & -1 & 0 & 0 & 0 & 0\\
    -1 & 2 & -1 & 0 & 0 & 0\\
    0 & -1 & 2 & -1 & 0 & 0\\
    0 & 0 & -1 & 2 & -1 & 0\\
    0 & 0 & 0 & -1 & 2 & -1\\
    0 & 0 & 0 & 0 & -1 & 5
    \end{pmatrix}
$$

In [5]:
n=6
d = np.ones((n))*2.0
e = np.ones((n-1))*(-1.0)
c = e.copy()
d[n-1] = 5.0
AInv = np.identity(n)
c,d,e = LUdecomp3(c,d,e)
for i in range(n):
    AInv[:,i] = LUsolve3(c,d,e,AInv[:,i])
print("La matriz inversa es \n",AInv)

La matriz inversa es 
 [[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


### Ejercicio 25
Invierta la matriz $\mathbf{A}$ usando descomposición LU con pivote.
$$
    \mathbf{A}=\begin{pmatrix}
    0.5 & 0 & 0.25\\
    0.3 & 0.4 & 0.45\\
    -0.1 & 0.2 & -0.15
    \end{pmatrix}
$$

In [6]:
def matInv(a):
    n = len(a[0])
    aInv = np.identity(n)
    a,seq = LUdecomp(a)
    for i in range(n):
        aInv[:,i] = LUsolve(a,aInv[:,i],seq)
    return aInv

A = np.array([[ 0.5, 0.0, 0.25],[0.3, 0.4, 0.45],[ -0.1, 0.2, -0.15]])
a=A.copy()
print("Ainv =\n",matInv(A))

Ainv =
 [[ 3.00000000e+00 -1.00000000e+00  2.00000000e+00]
 [ 1.38777878e-16  1.00000000e+00  3.00000000e+00]
 [-2.00000000e+00  2.00000000e+00 -4.00000000e+00]]


### Ejercicio 26
Invierta la matriz $\mathbf{A}$.
$$
    \mathbf{A}=\begin{pmatrix}
    4 & -1 & 0 & 0\\
    -1 & 4 & -1 & 0\\
    0 & -1 & 4 & -1\\
    0 & 0 & -1 & 4
    \end{pmatrix}
$$

In [7]:
d = np.ones((4))*4.0
e = np.ones((3))*(-1.0)
c = e.copy()
AInv = np.identity(4)
c,d,e = LUdecomp3(c,d,e)
for i in range(4):
    AInv[:,i] = LUsolve3(c,d,e,AInv[:,i])
print("La matriz inversa es \n",AInv)

La matriz inversa es 
 [[0.26794258 0.07177033 0.01913876 0.00478469]
 [0.07177033 0.28708134 0.07655502 0.01913876]
 [0.01913876 0.07655502 0.28708134 0.07177033]
 [0.00478469 0.01913876 0.07177033 0.26794258]]
