In [1]:
import numpy as np

def LUdecomp(a):
    "Realiza la descomposición LU por el método de Doolittle para una matriz a."
    n = len(a)
    for k in range(0,n-1):
        for i in range(k+1,n):
            if a[i,k] != 0.0:
                lam = a [i,k]/a[k,k]
                a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
                a[i,k] = lam
    return a

def LUsolve(a,b):
    "Resuelve un sistema de ecuaciones luego de la descomposición LU"
    n = len(a)
    for k in range(1,n):
        b[k] = b[k] - np.dot(a[k,0:k],b[0:k])
    b[n-1] = b[n-1]/a[n-1,n-1]
    for k in range(n-2,-1,-1):
        b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    return b

In [2]:
import math
def choleski(a):
    "Realiza la descomposición de Choleski para una matriz a."
    n = len(a)
    for k in range(n):
        try:
            a[k,k] = math.sqrt(a[k,k]- np.dot(a[k,0:k],a[k,0:k]))
        except ValueError:
            error.err("La matriz no es definida positiva.")
        for i in range(k+1,n):
            a[i,k] = (a[i,k] - np.dot(a[i,0:k],a[k,0:k]))/a[k,k]
    for k in range(1,n): a[0:k,k] = 0.0
    return a

def choleskiSol(L,b):
    "Soluciona un sistema de ecuaciones por medio de la descomposición de Choleski."
    n = len(b)
    for k in range(n):
        b[k] = (b[k] - np.dot(L[k,0:k],b[0:k]))/L[k,k]
    for k in range(n-1,-1,-1):
        b[k] = (b[k] - np.dot(L[k+1:n,k],b[k+1:n]))/L[k,k]
    return b

### Ejemplo 21
Escriba un programa que solucione $\mathbf{AX=B}$ con el método de descomposición de Doolittle y calcule $|\mathbf{A}|$. Pruebe el programa con
$$
    \mathbf{A}=\begin{pmatrix}
    3 & -1 & 4\\
    -2 & 0 & 5\\
    7 & 2 & -2
    \end{pmatrix}
    \quad
    \mathbf{B}=\begin{pmatrix}
    6 & -4\\
    3 & 2\\
    7 & -5
    \end{pmatrix}
$$

In [3]:
A = np.array([[3,-1,4],[-2,0,5],[7,2,-2]],dtype=float)
B = np.array([[6,3,7], [-4,2,-5]],dtype=float)
A = LUdecomp(A)
print("Descomposición de A:\n",A)
print("\nDeterminante de A =",np.linalg.det(A))
for i in range(len(B)):
    x = LUsolve(A,B[i])
    print("x",i+1,"=",x)

Descomposición de A:
 [[ 3.         -1.          4.        ]
 [-0.66666667 -0.66666667  7.66666667]
 [ 2.33333333 -6.5        38.5       ]]

Determinante de A = 52.50000000000007
x 1 = [1. 1. 1.]
x 2 = [-1.00000000e+00  1.00000000e+00  2.30695693e-17]


### Ejemplo 22
Use el método de descomposición de Choleski para resolver el sistema de ecuaciones $\mathbf{Ax=b}$, donde 
$$
    \mathbf{A}=\begin{pmatrix}
    1.44 & -0.36 & 5.52 & 0.00\\
    -0.36 & 10.33 & -7.78 & 0.00\\
    5.52 & -7.78 & 28.40 & 9.00\\
    0.00 & 0.00 & 9.00 & 61.00
    \end{pmatrix}
    \quad
    \mathbf{b}=\begin{pmatrix}
    0.04\\
    -2.15\\
    0\\
    0.88
    \end{pmatrix}
$$
Y verifique la solución.

In [4]:
A = np.array([[ 1.44, -0.36, 5.52, 0.0],[-0.36, 10.33, -7.78, 0.0],[ 5.52, -7.78, 28.40, 9.0],[ 0.0, 0.0, 9.0, 61.0]])
b = np.array([0.04, -2.15, 0.0, 0.88])
aOrig = A.copy()
L = choleski(A)
x = choleskiSol(L,b)
print("La solución del sistema es:",x)
print("\nVerificación Ax =\n",np.dot(aOrig,x))

La solución del sistema es: [ 3.09212567 -0.73871706 -0.8475723   0.13947788]

Verificación Ax =
 [ 4.00000000e-02 -2.15000000e+00 -3.55271368e-15  8.80000000e-01]


### Ejercicio 18
Use el método de descomposición de Doolittle para resolver el sistema de ecuaciones $\mathbf{Ax=b}$, donde 
$$
    \mathbf{A}=\begin{pmatrix}
    1 & 4 & 1\\
    1 & 6 & -1\\
    2 & -1 & 2
    \end{pmatrix}
    \quad
    \mathbf{b}=\begin{pmatrix}
    7\\
    13\\
    5
    \end{pmatrix}
$$

In [5]:
A=np.array([[1,4,1],[1,6,-1],[2,-1,2]],dtype=float)
b=np.array([7,13,5],dtype=float)
a=LUdecomp(A)
print("[L|U]=\n",a)

[L|U]=
 [[ 1.   4.   1. ]
 [ 1.   2.  -2. ]
 [ 2.  -4.5 -9. ]]


In [6]:
print("La solución del sistema es:",LUsolve(a,b))

La solución del sistema es: [ 5.  1. -2.]


### Ejercicio 19
Use el método de descomposición de Choleski para resolver el sistema de ecuaciones $\mathbf{Ax=b}$, donde 
$$
    \mathbf{A}=\begin{pmatrix}
    4 & -2 & 2\\
    -2 & 2 & -4\\
    2 & -4 & 11
    \end{pmatrix}
    \quad
    \mathbf{b}=\begin{pmatrix}
    7\\
    13\\
    5
    \end{pmatrix}
$$

In [7]:
A=np.array([[4,-2,2],[-2,2,-4],[2,-4,11]],dtype=float)
b=np.array([7,13,5],dtype=float)
a=choleski(A)
print("L=\n",a)

L=
 [[ 2.  0.  0.]
 [-1.  1.  0.]
 [ 1. -3.  1.]]


In [8]:
print("La solución del sistema es:",choleskiSol(a,b))

La solución del sistema es: [ 61.  169.5  51. ]


### Ejercicio 20
Escriba un programa que solucione $\mathbf{AX=B}$ donde
$$
    \mathbf{A}=\begin{pmatrix}
    6 & -4 & 1\\
    -4 & 6 & -4\\
    1 & -4 & 6
    \end{pmatrix}
    \quad
    \mathbf{B}=\begin{pmatrix}
    -14 & 22\\
    36 & -18\\
    6 & 7
    \end{pmatrix}
$$
_Solución_: Usando primero el método de Doolittle tenemos:

In [9]:
A = np.array([[6,-4,1],[-4,6,-4],[1,-4,6]],dtype=float)
B = np.array([[-14,36,6], [22,-18,7]],dtype=float)
a = LUdecomp(A)
print("Descomposición de A:\n",a)
for i in range(len(B)):
    x = LUsolve(a,B[i])
    print("x",i+1,"=",x)

Descomposición de A:
 [[ 6.         -4.          1.        ]
 [-0.66666667  3.33333333 -3.33333333]
 [ 0.16666667 -1.          2.5       ]]
x 1 = [10. 22. 14.]
x 2 = [ 3. -1.  0.]
