### Ejercicio 29
Use la descomposición QR para resolver el sistema de ecuaciones $\mathbf{Ax=b}$, donde 
$$
    \mathbf{A}=\begin{pmatrix}
    1 & 4 & 1\\
    1 & 6 & -1\\
    2 & -1 & 2
    \end{pmatrix}
    \quad
    \mathbf{b}=\begin{pmatrix}
    7\\
    13\\
    5
    \end{pmatrix}
$$

In [1]:
import numpy as np

A=np.array([[1,4,1],[1,6,-1],[2,-1,2]],dtype=float)
b=np.array([7,13,5],dtype=float)
Q,R = np.linalg.qr(A)
y=np.linalg.solve(Q,b)
x=np.linalg.solve(R,y)
print("Descomposición QR:\n Q=\n",Q)
print("R=\n",R,"\n")
print("La solución del sistema es:\n")
for i in range(len(x)):
    print("x",i+1,"=",x[i])

Descomposición QR:
 Q=
 [[-0.40824829 -0.40985242 -0.81569255]
 [-0.40824829 -0.71724173  0.56471022]
 [-0.81649658  0.56354707  0.12549116]]
R=
 [[-2.44948974 -3.26598632 -1.63299316]
 [ 0.         -6.5064071   1.43448345]
 [ 0.          0.         -1.12942045]] 

La solución del sistema es:

x 1 = 5.0
x 2 = 0.9999999999999999
x 3 = -1.9999999999999996


### Ejercicio 30
Clasifique el condicionamiento de las siguientes matrices:
$$\displaystyle \mathbf{A}=\begin{pmatrix}
    1 & 2 & 3\\
    2 & 3 & 4\\
    3 & 4 & 5
    \end{pmatrix}\qquad
    \mathbf{B}=\begin{pmatrix}
    2.11 & -0.80 & 1.72\\
    -1.84 & 3.03 & 1.29\\
    -1.57 & 5.25 & 4.30
    \end{pmatrix}\qquad
    \mathbf{C}=\begin{pmatrix}
    2 & -1 & 0\\
    -1 & 2 & -1\\
    0 & -1 & 2
    \end{pmatrix}\qquad
    \mathbf{D}=\begin{pmatrix}
    4 & 3 & -1\\
    7 & -2 & 3\\
    5 & -18 & 13
    \end{pmatrix}$$

In [2]:
A=np.array([[1,2,3],[2,3,4],[3,4,5]],dtype=float)
B=np.array([[2.11,-0.80,1.72],[-1.84,3.03,1.29],[-1.57,5.25,4.30]])
C=np.array([[2,-1,0],[-1,2,-1],[0,-1,2]],dtype=float)
D=np.array([[4,3,-1],[7,-2,3],[5,-18,13]],dtype=float)

#Matriz A
U,lam,V = np.linalg.svd(A)
print("Elementos diagonales de lambda A: ",lam)
print("Número condicional para A: ",max(lam)/min(lam),"\n")

#Matriz B
U,lam,V = np.linalg.svd(B)
print("Elementos diagonales de lambda B: ",lam)
print("Número condicional para B: ",max(lam)/min(lam),"\n")

#Matriz C
U,lam,V = np.linalg.svd(C)
print("Elementos diagonales de lambda A: ",lam)
print("Número condicional para C: ",max(lam)/min(lam),"\n")

#Matriz D
U,lam,V = np.linalg.svd(D)
print("Elementos diagonales de lambda D: ",lam)
print("Número condicional para D: ",max(lam)/min(lam))

Elementos diagonales de lambda A:  [9.62347538e+00 6.23475383e-01 3.97943080e-16]
Número condicional para A:  2.4183044944012284e+16 

Elementos diagonales de lambda B:  [7.82448153e+00 3.09450851e+00 2.43122220e-03]
Número condicional para B:  3218.332541480952 

Elementos diagonales de lambda A:  [3.41421356 2.         0.58578644]
Número condicional para C:  5.828427124746193 

Elementos diagonales de lambda D:  [2.33769332e+01 7.71485545e+00 4.30547196e-16]
Número condicional para D:  5.429586681719376e+16


Por los calculos hechos y por lo discutido sobre la utilidad de $\Lambda$ en el análisis de condicionamiento de una matriz, podemos decir ninguna matriz es singular; $\mathbf{A}$ y $\mathbf{D}$ están mal condicionadas \(y en menor medida $\mathbf{B}$).